export const CREATE_PAYMENT_REQUEST='CRATE_PAYMENT_REQUEST'
export const CREATE_PAYMENT_SUCCESS='CRATE_PAYMENT_SUCCESS'
export const CREATE_PAYMENT_FAILURE='CRATE_PAYMENT_FAILURE'

export const UPDATE_PAYMENT_REQUEST ='UPDATE_PAYMENT_REQUEST'
export const UPDATE_PAYMENT_SUCCESS ='UPDATE_PAYMENT_SUCCESS'
export const UPDATE_PAYMENT_FAILURE ='UPDATE_PAYMENT_FAILURE'




